version: '3.8'

services:
    app:
        build:
            context: .
        container_name: face-recognizer
        volumes:
          - "./static/uploads/temp:/usr/src/static/uploads/temp"
        command:
          - python3 app/create_db.py
        entrypoint: python -m app
        ports:
          - "5001:5000"
